### PR TITLE
Added remaining corpora except sanskrit

### PR DESCRIPTION
**Pull request by ghost**
I have taken care of all available corpora except Sanskrit(since it's not integrated with pip so at present I have ignored Sanskrit part). 
And I am using 

``` python
cltk.corpus.<lang>.corpora.<LANG>_CORPORA
```

instead of defining again for downloading/installing corpora(One draw back in this case is that, it downloads all the available corpora and some corpora may not be required and some corpora may be of huge size). But actually it was mentioned in <a href="https://github.com/cltk/cltk/issues/178">issue#178</a> that

<blockquote>
we can think of auto-installing all available CLTK-hosted corpora (perhaps the Dockerfile hitting a script which query available repos for each language and fetch them.)
</blockquote>

So I think downloading all available corpora is fine though it takes lot of time. What about your opinion ?

Also I have modified code a bit so that it looks simple.
If this is fine, I will merge it.

### CODE REVIEW

**Comment by kylepjohnson** [comment]
Do you feel like working on a function which will auto-discover and then install all available (remote) corpora? I think this repo would be a good place to try that.

**Comment by ghost** [comment]
Right now this function <code>install.py</code> does the same thing. That is it looks the available corpora and installs them. So the idea of looking the available is that, looking the metadeta present at 
/cltk/corpus/<lang>/corpora.py file for example /cltk/corpus/greek/corpora.py and downloads all the remotly available corpora as per GREEK_CORPORA list. Does this answer your question ?

**Comment by kylepjohnson** [comment]
Well done, this is good code you wrote!

**Comment by ghost** [comment]
Thank you sir.

**Pull request merged**
