### PR TITLE
Added badge to README and corrected run.sh

### PR DESCRIPTION
**Pull request by ghost**
- Added badge to README
- Corrected run.sh
- Corresponding comment : <a href="https://github.com/cltk/cltk_docker/pull/3#issuecomment-198839207">issuecomment-198839207</a>

Thanks.

### CODE REVIEW

**Comment by kylepjohnson** [comment]
Cool. I have added Travis, will trigger a build

**Comment by ghost** [comment]
Thank you sir.

**Comment by kylepjohnson** [comment]
Building on Travis now: https://travis-ci.org/cltk/cltk_docker

@achaitanyasai I'll leave it to you to make any corrections, if necessary.

**Comment by ghost** [comment]
Yeah, I am watching it and I will do corrections if necessary.
<b>UPD:</b> Build passed.

**Pull request merged**
